<?php
        define('USRID','user_id');
        //OTHER PARAMATERS
        define('ERROR','error');
        define('ERROR_USER_EXISTS','USER_ALREADY_EXISTS');
        define('USER_AGENT','ua');
        define('CURRENT_SOURCE','cs');
        define('ERROR_LINE','el');
        define('CURRENT_METHOD','cm');
        define('APPLICATION_VERSION','av');
        //RESPONSE OBJECT
        define('RESPONSE_STATUS','status');
        define('RESPONSE_DATA','entity');
        define('DATA','data');
        define('RESPONSE_NOTIFICATION','n');
        define('RESPONSE_CODE','c');
        //TERMS AND CONDITION
        define('TERMS_AND_CONDITION_PARAM','tac');
        define('PRIVACY_POLICAY_PARAM','pp');
        define('TERMS_AND_CONDITION_VERSION_PARAM','vtac');
        define('PRIVACY_POLICAY_VERSION_PARAM','vpp');
        define('TERMS_AND_CONDITION_DATE_PARAM','dtac');
        define('PRIVACY_POLICAY_DATE_PARAM','dpp');
        define('ENTITY','entity');
        define('NOTIFICATION_REGISTRATION_ID','NotificationRegistrationId');
        define('NOTIFICATION_DEVICE_OS','DeviceOS');
        //Articles
        define('ARTICLE_ID','ai');
        define('ALINEA_ID','alinea_id');
        define('TITRE_ID','titre_id');
        define('TITRE_NAME','titre_name');

        define('ARTICLE_TEXT','at');
        define('ALINEA_TEXT','alinea_text');
        define('TITRE_TEXT','tt');
        define('ALINEA_STATUS','alinea_status');
        define('article_STATUS','article_status');
        define('TITRE_STATUS','titre_status');
        define('CONSTITUTION_STATUS','constitution_status');
        define('ARTICLE_NUMBER','an');
        define('ALINEA_NUMBER','alinea_number');
        define('TITRE_NUMBER','titre_number');
        define('ALINEA_VERSION','alinea_version');
        define('PROPOSITION_ID','proposition_id');
        define('PROPOSITION_NUMBER','proposition_number');
        define('PROPOSITION_TEXT','proposition_text');
        define('PROPOSITION_VOTE','proposition_vote');
        define('PROPOSITION_USER','proposition_usr');
        define('YESVOTES_COUNT','yesvotes_count');
        define('NOVOTES_COUNT','novotes_count');
        define('ALLVOTES_COUNT','votesCount');
        define('TOTALS','totaux');
        define('REPORTED_COUNT','reported_count');
        define('PROPOSITION_COUNT','proposition_count');
        define('VERSION','v');
        define('FIRSTNAME','firstname');
        define('LASTNAME','lastname');
        define('PASSWORD','password');
        define('EMAIL','email');
        define('IS_PERSISTENT','is_persistent');
        define('DOB','dateofbirth');
        define('ISFRENCH','isfrench');
        define('CIVILITE','civilite');
        define('CODEPOSTAL','codePostal');
        define('COUNTRY','country');
        define('EMAIL_TOKEN','email_token');
        define('VOTE','vote');
        define('A_VOTE_OUI','yes');
        define('A_VOTE_NON','no');
        define('A_VOTE_SANS_OPINION','noOpinion');
        define('TOTALALINEA','totalAlinea');
        define('TOTALVOTES','totalvotes');
        define('N_A_PAS_VOTE','emptyVote');

        define('MESSAGE','message');
        define('CAPTCHA','captcha');
        define('SUBJECT','subject');
        define('WRONG_CAPTCHA','WRONG_CAPTCHA');